/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;


/**
 *
 * @author carlos franco
 */
public class FrmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
        this.setExtendedState(FrmAdministrador.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        BtnMunicipio = new javax.swing.JButton();
        Btncerrar = new javax.swing.JButton();
        BtnUsuarios = new javax.swing.JButton();
        BtnDepartamento1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setExtendedState(6);
        setFocusCycleRoot(false);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1160, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 1160, 730));

        BtnMunicipio.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnMunicipio.setText("Gestionar Municipio");
        BtnMunicipio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 51, 255)));
        BtnMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMunicipioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 33));

        Btncerrar.setText("CERRAR SESION");
        Btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtncerrarMouseClicked(evt);
            }
        });
        getContentPane().add(Btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        BtnUsuarios.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnUsuarios.setText("Gestionar Usuarios");
        BtnUsuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 51, 255)));
        BtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuariosActionPerformed(evt);
            }
        });
        getContentPane().add(BtnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 140, 33));

        BtnDepartamento1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BtnDepartamento1.setText("Gestionar Departamento");
        BtnDepartamento1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(0, 0, 204), new java.awt.Color(0, 51, 255)));
        BtnDepartamento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDepartamento1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDepartamento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 140, 33));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMunicipioActionPerformed
        FrmMunicipio ob= new FrmMunicipio();
        this.jDesktopPane1.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_BtnMunicipioActionPerformed

    private void BtncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtncerrarMouseClicked
        this.setVisible(false);
        FrmLogin log = new FrmLogin();
        log.setVisible(true);
        log.pack();
    }//GEN-LAST:event_BtncerrarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        this.setExtendedState(FrmAdministrador.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void BtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuariosActionPerformed
        FrmUsuario ob= new FrmUsuario();
        this.jDesktopPane1.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_BtnUsuariosActionPerformed

    private void BtnDepartamento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDepartamento1ActionPerformed
        FrmDepartamento ob= new FrmDepartamento();
        this.jDesktopPane1.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_BtnDepartamento1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDepartamento1;
    private javax.swing.JButton BtnMunicipio;
    private javax.swing.JButton BtnUsuarios;
    private javax.swing.JButton Btncerrar;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
