/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

/**
 *
 * @author carlos franco
 */
public class FrmAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBtnPeriodo = new javax.swing.JButton();
        jBtnCerrar = new javax.swing.JButton();
        jBtnUsuario = new javax.swing.JButton();
        jBtnCandidato = new javax.swing.JButton();
        jBtnVotante = new javax.swing.JButton();
        jBtnPartido = new javax.swing.JButton();
        jBtnJRV = new javax.swing.JButton();
        jBtnEncargado = new javax.swing.JButton();
        jBtnMunicipio = new javax.swing.JButton();
        jBtnDepartamento = new javax.swing.JButton();
        jBtnCentro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jBtnDelegado1 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jBtnPeriodo.setBackground(new java.awt.Color(0, 51, 102));
        jBtnPeriodo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnPeriodo.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPeriodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        jBtnPeriodo.setText("GESTIONAR PERIODO");
        jBtnPeriodo.setBorder(null);
        jBtnPeriodo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnPeriodo.setIconTextGap(75);
        jBtnPeriodo.setRolloverEnabled(false);

        jBtnCerrar.setBackground(new java.awt.Color(0, 51, 102));
        jBtnCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/login (1).png"))); // NOI18N
        jBtnCerrar.setText("CERRAR SESION");
        jBtnCerrar.setBorder(null);
        jBtnCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnCerrar.setRolloverEnabled(false);
        jBtnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCerrarMouseClicked(evt);
            }
        });

        jBtnUsuario.setBackground(new java.awt.Color(0, 51, 102));
        jBtnUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (2).png"))); // NOI18N
        jBtnUsuario.setText("GESTIONAR USUARIO");
        jBtnUsuario.setBorder(null);
        jBtnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnUsuario.setIconTextGap(75);
        jBtnUsuario.setRolloverEnabled(false);

        jBtnCandidato.setBackground(new java.awt.Color(0, 51, 102));
        jBtnCandidato.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCandidato.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCandidato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/candidato.png"))); // NOI18N
        jBtnCandidato.setText("GESTIONAR CANDIDATO");
        jBtnCandidato.setBorder(null);
        jBtnCandidato.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnCandidato.setIconTextGap(58);
        jBtnCandidato.setRolloverEnabled(false);

        jBtnVotante.setBackground(new java.awt.Color(0, 51, 102));
        jBtnVotante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnVotante.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVotante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/voto.png"))); // NOI18N
        jBtnVotante.setText("GESTIONAR VOTANTE");
        jBtnVotante.setBorder(null);
        jBtnVotante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnVotante.setIconTextGap(75);
        jBtnVotante.setRolloverEnabled(false);

        jBtnPartido.setBackground(new java.awt.Color(0, 51, 102));
        jBtnPartido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnPartido.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPartido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bandera.png"))); // NOI18N
        jBtnPartido.setText("GESTIONAR PARTIDO POLITICO");
        jBtnPartido.setBorder(null);
        jBtnPartido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnPartido.setIconTextGap(10);
        jBtnPartido.setRolloverEnabled(false);

        jBtnJRV.setBackground(new java.awt.Color(0, 51, 102));
        jBtnJRV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnJRV.setForeground(new java.awt.Color(255, 255, 255));
        jBtnJRV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/info.png"))); // NOI18N
        jBtnJRV.setText("GESTIONAR JRV");
        jBtnJRV.setBorder(null);
        jBtnJRV.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnJRV.setIconTextGap(110);
        jBtnJRV.setRolloverEnabled(false);

        jBtnEncargado.setBackground(new java.awt.Color(0, 51, 102));
        jBtnEncargado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnEncargado.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEncargado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/empleado.png"))); // NOI18N
        jBtnEncargado.setText("GESTIONAR ENCARGADO");
        jBtnEncargado.setBorder(null);
        jBtnEncargado.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnEncargado.setIconTextGap(55);
        jBtnEncargado.setRolloverEnabled(false);

        jBtnMunicipio.setBackground(new java.awt.Color(0, 51, 102));
        jBtnMunicipio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        jBtnMunicipio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pueblo.png"))); // NOI18N
        jBtnMunicipio.setText("GESTIONAR MUNICIPIO");
        jBtnMunicipio.setBorder(null);
        jBtnMunicipio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnMunicipio.setIconTextGap(64);
        jBtnMunicipio.setRolloverEnabled(false);

        jBtnDepartamento.setBackground(new java.awt.Color(0, 51, 102));
        jBtnDepartamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDepartamento.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDepartamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/europa.png"))); // NOI18N
        jBtnDepartamento.setText("GESTIONAR DEPARTAMENTO");
        jBtnDepartamento.setBorder(null);
        jBtnDepartamento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnDepartamento.setIconTextGap(30);
        jBtnDepartamento.setRolloverEnabled(false);

        jBtnCentro.setBackground(new java.awt.Color(0, 51, 102));
        jBtnCentro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnCentro.setForeground(new java.awt.Color(255, 255, 255));
        jBtnCentro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/casa.png"))); // NOI18N
        jBtnCentro.setText("GESTIONAR CENTRO DE VOTACION");
        jBtnCentro.setBorder(null);
        jBtnCentro.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnCentro.setMaximumSize(new java.awt.Dimension(181, 15));
        jBtnCentro.setMinimumSize(new java.awt.Dimension(181, 15));
        jBtnCentro.setRolloverEnabled(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario (1).png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mas.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));

        jBtnDelegado1.setBackground(new java.awt.Color(0, 51, 102));
        jBtnDelegado1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jBtnDelegado1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnDelegado1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/consola-ecualizador-con-tres-interruptores-en-diferentes-niveles.png"))); // NOI18N
        jBtnDelegado1.setText("GESTIONAR TIPO CANDIDATO");
        jBtnDelegado1.setBorder(null);
        jBtnDelegado1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jBtnDelegado1.setIconTextGap(28);
        jBtnDelegado1.setRolloverEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnCentro, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(jBtnDelegado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnPartido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnJRV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(jBtnEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnCandidato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnVotante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBtnPeriodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(49, 49, 49)
                .addComponent(jBtnCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnDelegado1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnJRV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnVotante, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jBtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1116, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCerrarMouseClicked
        this.setVisible(false);
        FrmLogin log = new FrmLogin();
        log.setVisible(true);
        log.pack();
    }//GEN-LAST:event_jBtnCerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCandidato;
    private javax.swing.JButton jBtnCentro;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnDelegado1;
    private javax.swing.JButton jBtnDepartamento;
    private javax.swing.JButton jBtnEncargado;
    private javax.swing.JButton jBtnJRV;
    private javax.swing.JButton jBtnMunicipio;
    private javax.swing.JButton jBtnPartido;
    private javax.swing.JButton jBtnPeriodo;
    private javax.swing.JButton jBtnUsuario;
    private javax.swing.JButton jBtnVotante;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
