/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vista;

import com.controlador.DaoPartidoPolitico;
import com.modelo.PartidoPolitico;
import java.awt.image.BufferedImage;
import java.awt.image.DataBufferByte;
import java.awt.image.WritableRaster;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author Mauricio
 */
public class FrmPartidoPolitico extends javax.swing.JInternalFrame {
    
    public byte[] fotoPartido;
    /**
     * Creates new form FrmPartidoPolitico
     */
    public FrmPartidoPolitico() {
        initComponents();
        mostrarPartidos();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        imagenComponent = new com.utils.ImageComponent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuardar.setText("jButton1");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });

        imagenComponent.setMaximumSize(new java.awt.Dimension(120, 120));
        imagenComponent.setMinimumSize(new java.awt.Dimension(120, 120));
        imagenComponent.setName("imagenComponent"); // NOI18N

        javax.swing.GroupLayout imagenComponentLayout = new javax.swing.GroupLayout(imagenComponent);
        imagenComponent.setLayout(imagenComponentLayout);
        imagenComponentLayout.setHorizontalGroup(
            imagenComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        imagenComponentLayout.setVerticalGroup(
            imagenComponentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(imagenComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addComponent(btnGuardar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagenComponent, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar))
                .addContainerGap(299, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked
        try {
            guardarPartido();
        } catch (IOException ex) {
            Logger.getLogger(FrmPartidoPolitico.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FrmPartidoPolitico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPartidoPolitico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPartidoPolitico().setVisible(true);
            }
        });
    }
    
    public void mostrarPartidos(){
        DaoPartidoPolitico dao = new DaoPartidoPolitico();
        PartidoPolitico partido = new PartidoPolitico();
        // ACA DEBERÍA IR LA LOGICA PARA LLENAR LA TABLA
        // PARA MIENTRAS SOLO VOY A PONER UN EJEMPLO DE COMO MOSTRAR UNA IMAGEN
        List ls;
        try{
            ls = dao.mostrarPartido();
            for(int i = 0; i < ls.size(); i++){
                partido = (PartidoPolitico)ls.get(i);
                imagenComponent.updateImage(fotoPartido);
            }
        }catch(Exception e){
            
        }
    }
    
    public void guardarPartido() throws IOException, Exception{
        //EL PARTIDO SE GUARDARA VARIAS VECES PORQUE NO SE HA CREADO UN METODO
        //PARA MODIFICAR NI VALIDACIONES
        DaoPartidoPolitico dao = new DaoPartidoPolitico();
        PartidoPolitico partido = new PartidoPolitico();
        try{
            guardarFoto();
            partido.setPartido("Mauro guapo");
            partido.setPresidente("Mauro presidnete");
            partido.setFotoPartido(fotoPartido);
            partido.setActivo(1);
            dao.insertarPartido(partido);
            mostrarPartidos();
        }catch(Exception e){
            throw e;
        }
        
    }
    
    public void guardarFoto() throws IOException{
        JFileChooser file = new JFileChooser();
        file.setDialogTitle("Seleccione la imagen a guardar");
        
        int seleccion = file.showSaveDialog(file);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File foto = file.getSelectedFile();
            fotoPartido = extraerBytes(foto);
        }
    }
    
    public byte[] extraerBytes (File img) throws IOException {
        //Obtener imagen
        BufferedImage bufferedImage = ImageIO.read(img);

        // obtener DataBufferBytes del Raster
        WritableRaster raster = bufferedImage .getRaster();
        DataBufferByte data   = (DataBufferByte) raster.getDataBuffer();

        return ( data.getData() );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private com.utils.ImageComponent imagenComponent;
    // End of variables declaration//GEN-END:variables
}
