
package com.vista;

import com.controlador.DaoUsuario;
import com.modelo.Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Nombre de la Clase: FrmUsuario
 * Version: 1.0
 * Fecha: 05/12/18
 * CopyRight: ITCA-FEPADE
 * @author Administrador
 */
public class FrmUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuario
     */
    public FrmUsuario() {
        initComponents();
        tablaE();
        
    }
    
    DaoUsuario daou = new DaoUsuario();
    Usuario user = new Usuario();

    public void insertar()
    {
        
        try 
        {
           user.setCodigousuario(Integer.parseInt(this.jTXTidUsuario.getText().trim()));
           user.setUsuario(this.jTXTUsuario.getText().trim());
           user.setClave(this.jTXTClave.getText().trim());
           user.setTipo(this.jCBTipo.getSelectedItem().toString());
           daou.insertarUsuario(user);
           JOptionPane.showMessageDialog(null,"Datos Insertado Correctamente");
           tablaE();
           limpiar();
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this,e.toString(),"ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void llenarTabla()
 {
      int fila=this.jTableusuario.getSelectedRow();
      this.jTXTidUsuario.setText(String.valueOf(this.jTableusuario.getValueAt(fila, 0)));
      this.jTXTUsuario.setText(String.valueOf(this.jTableusuario.getValueAt(fila, 1)));
      this.jTXTClave.setText(String.valueOf(this.jTableusuario.getValueAt(fila, 2)));
      this.jCBTipo.setSelectedItem(String.valueOf(this.jTableusuario.getValueAt(fila, 3)));
 }
     public void limpiar()
    {
      this.jTXTidUsuario.setText("");
      this.jTXTUsuario.setText("");
      this.jTXTClave.setText("");
      this.jCBTipo.setSelectedIndex(0);
    }
    
     public void modificar()
    {
         try 
        {
            user.setCodigousuario(Integer.parseInt(this.jTXTidUsuario.getText().trim()));
            user.setUsuario(this.jTXTUsuario.getText().trim());
            user.setClave(this.jTXTClave.getText().trim());
            user.setTipo(this.jCBTipo.getSelectedItem().toString());
            int SiONo=JOptionPane.showConfirmDialog(this, "Desea modificar el Usuario",
                    "Modificar Usuario",JOptionPane.YES_NO_OPTION);
            if(SiONo==0)
            {
                daou.modificarUsuario(user);
                JOptionPane.showMessageDialog(rootPane, "Usuario modificado con exito", 
                        "Confirmación",
                        JOptionPane.INFORMATION_MESSAGE);
                tablaE();
                limpiar();
            }
            else
            {
                limpiar();
            }
        } catch (Exception ex) {
           ex.printStackTrace();
        }
    }
    public void eliminar()
    {

        try 
        {
            user.setCodigousuario(Integer.parseInt(this.jTXTidUsuario.getText()));
            int SiONo=JOptionPane.showConfirmDialog(this, "Desea eliminar el Usuario",
                    "Eliminar Usuario",JOptionPane.YES_NO_OPTION);
            if(SiONo==0)
            {
                daou.eliminarUsuario(user);
                JOptionPane.showMessageDialog(rootPane,"Eliminado con exito" , "Confirmación",
                        JOptionPane.INFORMATION_MESSAGE);
                tablaE();
                limpiar();
            }
            else
            {
                limpiar();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.toString(), "Error",
                    JOptionPane.ERROR_MESSAGE);
        } 
    }
public void tablaE()
    {
        String [] columnas={"CodigoUsuario","NombreUsuario","ClaveUsuario","TipoUsuario"} ;
        Object[] obj=new Object[4];
        DefaultTableModel tabla=new DefaultTableModel(null,columnas);
        List ls;
        try 
        {
           ls =daou.mostrarUsuario();
            for(int i=0;i<ls.size();i++)
            {   user=(Usuario)ls.get(i);
                obj[0]=user.getCodigousuario();
                obj[1]=user.getUsuario();
                obj[2]=user.getClave();
                obj[3]=user.getTipo();
                tabla.addRow(obj);
            }
        
            ls=daou.mostrarUsuario();
            this.jTableusuario.setModel(tabla);
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Error al mostrar datos" + e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTXTidUsuario = new javax.swing.JTextField();
        jTXTUsuario = new javax.swing.JTextField();
        jTXTClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCBTipo = new javax.swing.JComboBox<>();
        BtnIngresar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableusuario = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("GESTIONAR USUARIOS");

        jTXTidUsuario.setText(" ");

        jTXTUsuario.setText(" ");

        jTXTClave.setText(" ");

        jLabel2.setText("Codigo de Usuario:");

        jLabel3.setText("Nombre de Usuario:");

        jLabel4.setText("Clave de Usuario:");

        jLabel5.setText("Tipo de Usuario:");

        jCBTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Tipo..", "Administrador", "Delegado" }));

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnIngresarMouseClicked(evt);
            }
        });

        BtnModificar.setText("Modificar");
        BtnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnModificarMouseClicked(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnEliminarMouseClicked(evt);
            }
        });

        jTableusuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Usuario", "Nombre Usuario", "Clave Usuario", "Tipo Usuario"
            }
        ));
        jTableusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableusuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableusuario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTXTUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(jTXTClave)
                                        .addComponent(jTXTidUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(136, 136, 136))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnIngresar)
                                .addGap(80, 80, 80)
                                .addComponent(BtnModificar)
                                .addGap(64, 64, 64)
                                .addComponent(BtnEliminar)
                                .addGap(107, 107, 107))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXTidUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXTUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXTClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIngresar)
                    .addComponent(BtnModificar)
                    .addComponent(BtnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnIngresarMouseClicked
        insertar();
    }//GEN-LAST:event_BtnIngresarMouseClicked

    private void jTableusuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableusuarioMouseClicked
        llenarTabla();
    }//GEN-LAST:event_jTableusuarioMouseClicked

    private void BtnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnModificarMouseClicked
        modificar();
    }//GEN-LAST:event_BtnModificarMouseClicked

    private void BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnEliminarMouseClicked
        eliminar();
    }//GEN-LAST:event_BtnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JComboBox<String> jCBTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTXTClave;
    private javax.swing.JTextField jTXTUsuario;
    private javax.swing.JTextField jTXTidUsuario;
    private javax.swing.JTable jTableusuario;
    // End of variables declaration//GEN-END:variables
}
